extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier/@typescript-eslint'
plugins:
  - 'prettier'
env:
  node: true
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: 'module'
globals:
  module: true
  inject: true
rules:
  prettier/prettier:
    - error
    - semi: true
      trailingComma: 'es5'
      singleQuote: true
      printWidth: 120
